services:
  flask:
    build: .
    container_name: Flask_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://maria:Appsecrets@mariadb/My_maria
      FLASK_APP: run.py

    depends_on:
        mariadb:
         condition: service_healthy

  react:
    build: ./gym_frontend_vite
    container_name: React_front
    env_file:
      - ./gym_frontend_vite/.env.docker
    ports:
      - "5173:5173"
    depends_on:
      - flask
  mariadb:
     
     image: mariadb:latest
     healthcheck:
       test: ["CMD" , "mariadb-admin","ping","-h","127.0.0.1","-u","root","-p1234Root"]
       interval: 20s
       timeout: 10s
       retries: 5
     container_name: database_maria
     environment:
       MYSQL_ROOT_PASSWORD: 1234Root
       MYSQL_DATABASE: My_maria
       MYSQL_USER: maria
       MYSQL_PASSWORD: Appsecrets
     volumes:
       - maria_data:/var/lib/mysql

volumes:
   maria_data:  
    
